### ISSUE TITLE
Make single and double-underline styling detectable for screen readers

### ISSUE THREAD

**Issue by openstaxalina** [openstax/ce-styles#127]
@Bkblodget commented on [Fri Oct 22 2021](https://github.com/openstax/unified/issues/1740)

# Description
This is an a11y update for multiple books in the library.

**Single Underline locations:**
Biology(493/493. Found 12)
- [m44405](https://legacy.cnx.org/content/m44405/latest/#fs-id2029814) Studying Cells 
- [m44431](https://legacy.cnx.org/content/m44431/latest/#fs-id1595819) Energy in Living Systems 
- [m44431](https://legacy.cnx.org/content/m44431/latest/#fs-id1595819) Energy in Living Systems 
- [m44432](https://legacy.cnx.org/content/m44432/latest/#fs-id2316327) Glycolysis 
- [m87357](https://legacy.cnx.org/content/m87357/latest/#fs-id1671263) Key Terms 

Astronomy(200/404. Found 7)
- [m59792](https://legacy.cnx.org/content/m59792/latest/#fs-id1163975674170) The Behavior of Light 

American Government 2e(204/204. Found 1)
- [m72423](https://legacy.cnx.org/content/m72423/latest/#fs-id1163758400666) Intergovernmental Relationships 

American Government(204/204. Found 1)
- [m58969](https://legacy.cnx.org/content/m58969/latest/#fs-id1163758400666) Intergovernmental Relationships 

Algebra and Trigonometry(172/172. Found 15)
- [m51261](https://legacy.cnx.org/content/m51261/latest/#fs-id1165137844421) Functions and Function Notation 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51284](https://legacy.cnx.org/content/m51284/latest/#fs-id1526800) Right Triangle Trigonometry 
- [m51286](https://legacy.cnx.org/content/m51286/latest/#fs-id931590) The Other Trigonometric Functions 
- [m49448](https://legacy.cnx.org/content/m49448/latest/#fs-id1165137443996) Counting Principles 

# Acceptance Criteria

- [ ] All screen readers detect and read when text has a single underline
- [ ] All screen readers detect and read when text has a double underline

# Acceptance Tests

**1**: “English Composition (Writing Guide with Handbook)” - screen reader should read single and double underlines
**categories**: Book Content, Accessibility, Navigation
> GIVEN  {base_url}/books/writing-guide/pages/6-6-editing-focus-subject-verb-agreement
> AND some words have  single and double underlines.(for eg. “The bus leaves in five minutes” - bus (single), leaves (double)
> WHEN use a screenreader
> THEN screen reader reads the underlines

# Epic Doc
URL

# Pipeline
1A-PRE DESIGN
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

2B-REVIEW
  - [ ] UX approves change
  - [ ] QA approves change
  - [ ] PDM approves change
  
3A-PEND RELEASE
  - [ ] QA verifies that the acceptance tests are imported into TestRail
  
# Process 
[Work Management for Unified](https://github.com/openstax/unified/blob/master/CONTRIBUTING.md)

---

@lwtchu commented on [Thu Nov 04 2021](https://github.com/openstax/unified/issues/1740#issuecomment-961228729)

corresponding issue: https://github.com/openstax/recipes/issues/137 

---

@openstaxalina commented on [Tue Dec 07 2021](https://github.com/openstax/unified/issues/1740#issuecomment-988238406)

Might make sense to do this at the same time as https://github.com/openstax/unified/issues/1768

---

@openstaxalina commented on [Thu Feb 10 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1035129670)

This card isn't ready for work -- we still need to add the a11y tags via the recipe in these books. @lwtchu is creating a separate card for Writing Guide specifically (will include links to content w/ underline & double-underline).

---

@TomWoodward commented on [Tue Jun 28 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1168791817)

@Malar-Natarajan this is done right?

---

@Malar-Natarajan commented on [Tue Jun 28 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1169004896)

@TomWoodward The pages mentioned in the issue description in this card are not yet done.

[Card that is linked as closed above](https://github.com/openstax/unified/issues/1768) was specific to Writing Guide.

---

@erikayvonne commented on [Mon Aug 15 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1215637314)

@lwtchu do you know if whatever formatting books are using for single/double underline, other books are using it too?

---

@TomWoodward commented on [Mon Aug 15 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1215637933)

alternatively it might be handled by the new alternate display logic we're working on

---

@lwtchu commented on [Mon Aug 15 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1215761150)

for the content-switch thing we only enabled this for writing guide - we could roll it out to the other books once it's ready to go? and the card will go to ce styles if that's ok

---

@erikayvonne commented on [Wed Sep 14 2022](https://github.com/openstax/unified/issues/1740#issuecomment-1247011301)

following up to this - @TomWoodward do you know if this is handled per your previous comment? if so, it would be great to roll it out to other books and send this card to ce styles if that still sounds like a good plan.

**Comment by philschatz** [comment]
[Section 6-6](https://rex-web.herokuapp.com/books/ee7ce46b-0972-4b2c-bc6e-8998c785cd57@833cc3c/pages/008e5069-1d14-4234-8a94-151a5b776f6a?archive=https://openstax.org/apps/archive/20220815.182343#para-00014) has an example of single and double underlines.

From our discussion today the remaining work on this card is to make sure that all single-underlines in our books have the same screenreader-only elements inside the `<u>` tag that say "underline" and "end underline"

**Comment by lwtchu** [comment]
Cards should be in cnx-recipes. Opened a cleaner card there: https://github.com/openstax/cnx-recipes/issues/4916
